# This file was generated by GoReleaser. DO NOT EDIT.
cask "rain" do
  version "2.4.1"

  on_macos do
    sha256 "f20ef729b32b61a8b7a126b5ea306dd2abb48224af428b742225645f150eb54b"
    url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_macos.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "afe0d12dc7e46a5fd6a568cb3f6636be7b47d073310978cf5f6dea0aea5a4654"
      url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_linux.tar.gz"
    end
  end

  name "rain"
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rain"
  generate_completions_from_executable "rain", "bash-autocomplete",
    shell_parameter_format: :none,
    shells: [:bash]

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rain"]
    end
  end

  # No zap stanza required

end
