# This file was generated by GoReleaser. DO NOT EDIT.
cask "rain" do
  version "2.4.2"

  on_macos do
    sha256 "266c40adee9107833d89755b28c9d45efeca04e974195f075cd48f8cf082042a"
    url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_macos.tar.gz"
  end
  on_linux do
    on_intel do
      sha256 "5690afc30aa6915e5842d7513a4d6f195e8988858688afd336e421b9b7aab105"
      url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_linux.tar.gz"
    end
  end

  name "rain"
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rain"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rain"]
    end
  end
  generate_completions_from_executable "rain", "bash-autocomplete",
    shell_parameter_format: :none,
    shells: [:bash]

  # No zap stanza required
end
