# This file was generated by GoReleaser. DO NOT EDIT.
cask "rain" do
  version "2.4.3"

  on_macos do
    sha256 "034f44f283abee23f8cc990c0360585b6e18ccc8d1f4845b690b98a178e4f4cf"
    url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_macos.tar.gz"
  end
  on_linux do
    on_intel do
      sha256 "072e9b263539c8e34e3b4028c283274e60c3a7e4c69b9a9cd71f1730a4bbb4de"
      url "https://github.com/cenkalti/rain/releases/download/v#{version}/rain_#{version}_linux.tar.gz"
    end
  end

  name "rain"
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rain"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rain"]
    end
  end
  generate_completions_from_executable "rain", "bash-autocomplete",
    shell_parameter_format: :none,
    shells: [:bash]

  # No zap stanza required
end
