# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rain < Formula
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"
  version "1.12.13"

  on_macos do
    url "https://github.com/cenkalti/rain/releases/download/v1.12.13/rain_1.12.13_macos.tar.gz"
    sha256 "6ac1d8bf1c314edcddb1714abc00b0915ae8b5f448680d7828639cd9df07f6ca"

    def install
      bin.install "rain"
      output = Utils.popen_read("#{bin}/rain bash-autocomplete")
      (bash_completion/"rain").write output
      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Rain
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cenkalti/rain/releases/download/v1.12.13/rain_1.12.13_linux.tar.gz"
      sha256 "1287fac5c16499a83f78ea7f3d4961640bf79975e9bb82e70696d5bbdd1e4901"

      def install
        bin.install "rain"
        output = Utils.popen_read("#{bin}/rain bash-autocomplete")
        (bash_completion/"rain").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/rain --version"
  end
end
