# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rain < Formula
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"
  version "2.2.1"

  on_macos do
    url "https://github.com/cenkalti/rain/releases/download/v2.2.1/rain_2.2.1_macos.tar.gz"
    sha256 "0ec0b5a5304e615fd195e7174e5246637f3d9820359ed0c99ac86b04e8840a42"

    def install
      bin.install "rain"
      output = Utils.popen_read("#{bin}/rain bash-autocomplete")
      (bash_completion/"rain").write output
      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Rain
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cenkalti/rain/releases/download/v2.2.1/rain_2.2.1_linux.tar.gz"
        sha256 "ef14301c0ed5c1cd8df6ae9ab47f3bdc498ffdba6ab09472197632e49e9ad2ce"

        def install
          bin.install "rain"
          output = Utils.popen_read("#{bin}/rain bash-autocomplete")
          (bash_completion/"rain").write output
          prefix.install_metafiles
        end
      end
    end
  end

  test do
    system "#{bin}/rain --version"
  end
end
