# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rain < Formula
  desc "BitTorrent client"
  homepage "https://github.com/cenkalti/rain"
  version "1.11.1-alpha.2"

  on_macos do
    url "https://github.com/cenkalti/rain/releases/download/v1.11.1-alpha.2/rain_1.11.1-alpha.2_macos.tar.gz"
    sha256 "09e91e8d8e5b92d7978ac005251b2aebf0ff3afebfb0d3ae413ef716dd4115eb"

    def install
      bin.install "rain"
      output = Utils.popen_read("#{bin}/rain bash-autocomplete")
      (bash_completion/"rain").write output
      prefix.install_metafiles
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Rain
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/cenkalti/rain/releases/download/v1.11.1-alpha.2/rain_1.11.1-alpha.2_linux.tar.gz"
      sha256 "7752182aecb1815838bb1058ac221884bf0ae1a6c9a389ea80d08375a9dbfac0"

      def install
        bin.install "rain"
        output = Utils.popen_read("#{bin}/rain bash-autocomplete")
        (bash_completion/"rain").write output
        prefix.install_metafiles
      end
    end
  end

  test do
    system "#{bin}/rain --version"
  end
end
